### PR TITLE
Supports legacy lz4 decompression

### PR DESCRIPTION
**Pull request by dantengsky**
not really a PR, just test CI

### CODE REVIEW

**Comment by dantengsky** [comment]
sorry, I should have open this PR in another repo first

**Comment by dantengsky** [comment]
PR is ready for review.

**Summary**

For issue:

- #152

A new feature `lz4_with_legacy_decompression` is introduced, which will enable the legacy lz4 decompression (and Lz4raw as well) algorithm.

**Comment by dantengsky** [comment]
Apologize for the late response!

Apparently, I failed to describe this pr clearly : (.  For `leacy`, I mean the lz4 decompression behavior before PR
- #https://github.com/jorgecarleitao/parquet2/pull/95

But, seems the [`Lz4HadoopCodec`](https://github.com/apache/arrow/blob/bf18e6e4b5bb6180706b1ba0d597a65a4ce5ca48/cpp/src/arrow/util/compression_lz4.cc#L411) are more of interest? I 'd like to have a try.
 
> A couple of points:
> 
> * On the read side, would it make sense to infer which format is being used and act based on that?

Hope I get it right, does it mean things like these?

https://github.com/apache/arrow/blob/bf18e6e4b5bb6180706b1ba0d597a65a4ce5ca48/cpp/src/arrow/util/compression_lz4.cc#L417-L418


> * On the write side, I think that this would be better supported via a new variant on the `Enum` with compression - something like `LegacyLz4` and `Lz4`.

IMHO, Lz4 compression codecs other than `Lz4Raw` should not be used, there've brought too many troubles :)


> * We will need to think about how we are going to test this behavior - ideally we should write a compressed file and try to read it from pyarrow or spark - the roundtrip of the algorithm itself is imo insufficient because it may not roundtrip with other implementations.

Yeah, I do not have a better idea of gererating legacy lz4 compressed data, seems the lz4 of latest pyarrrow means `Lz4Raw`? 
Maybe c++/java could be used in the CI? maybe too "heavy" though.

Currently, three files of `parquet-testing` are used in the testing of decompression:

- [non_hadoop_lz4_compressed.parquet](https://github.com/apache/parquet-testing/blob/8e7badc6a3817a02e06d17b5d8ab6b6dc356e890/data/non_hadoop_lz4_compressed.parquet)
- [hadoop_lz4_compressed.parquet](https://github.com/apache/parquet-testing/blob/8e7badc6a3817a02e06d17b5d8ab6b6dc356e890/data/hadoop_lz4_compressed.parquet)
- [hadoop_lz4_compressed_larger.parquet](https://github.com/apache/parquet-testing/blob/8e7badc6a3817a02e06d17b5d8ab6b6dc356e890/data/hadoop_lz4_compressed_larger.parquet)

**Comment by jorgecarleitao** [comment]
I am 100% with you - 

* infer like cpp does
* let's not write the old format and only support the read path

We are testing in integration against c++:
* here: https://github.com/jorgecarleitao/parquet2/blob/main/tests/write_pyarrow.py we have a selection of configurations we write from c++
* here: https://github.com/jorgecarleitao/parquet2/blob/main/tests/it/read/mod.rs#L380 we read them

The roundtrip test over our writer is here: https://github.com/jorgecarleitao/parquet2/blob/main/tests/it/write/mod.rs#L125

> Yeah, I do not have a better idea of generating legacy lz4 compressed data, seems the lz4 of the latest pyarrrow means Lz4Raw?

We could use a lower version of pyarrow - a new step in the CI where we install an older version of pyarrow  (imo it is a good test to confirm that we support older versions, specially when they change like that).

**Comment by dantengsky** [comment]
> We could use a lower version of pyarrow - a new step in the CI where we install an older version of pyarrow (imo it is a good test to confirm that we support older versions, specially when they change like that).

Thanks, I'll try it

**Comment by jorgecarleitao** [comment]
This is amazing. Thank you so much, @dantengsky 🙇

**Comment by dantengsky** [comment]
@jorgecarleitao  appreciate your kindness

**Pull request merged**
