### PR TITLE
WIP: Use lz4_flex for `wasm32`

### PR DESCRIPTION
**Pull request by kylebarron**
Disclaimer: I'm new to Rust but motivated to get LZ4 Parquet decompression working in wasm. 🙂 

I'm working on [wasm bindings](https://github.com/kylebarron/parquet-wasm) to `arrow2`/`parquet2`. So far it appears that all other compressions other than LZ4 are working. I tried to switch to `lz4_flex` on this branch but I'm not sure I gated the wasm target correctly. Tests seem to pass on this branch but when I try to load a Parquet file with LZ4 encoding on the web I get an error `Uncaught (in promise) External format error: underlying IO error: WrongMagicNumber`. Maybe I'm using the wrong `lz4_flex` APIs.

Ref #85

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Thanks a lot for the PR!

Would it be possible to use a feature flag instead of a conditional on the target? Folks not in wasm may want to use lz4_flex regardless of wasm, so maybe a feature could make more sense here?

This also allows us to add to the CI to run the tests with and without this flag, thereby covering both branches without having to run the tests under wasm.

**Comment by kylebarron** [comment]
> Would it be possible to use a feature flag instead of a conditional on the target?
> This also allows us to add to the CI to run the tests with and without this flag

Yes that makes a ton of sense. I've tried to update this to use a feature flag instead, where if `lz4` and `lz4_flex` features are both specified, then `lz4` takes precedence.

I'm not sure the optimal way to add a test for this; I added a CI unit test call with no default features and with lz4_flex added instead of lz4.

I'm also still not sure I'm using the `lz4_flex` API correctly 😄 .

**Comment by jorgecarleitao** [comment]
Sorry for the delay, I am focused on releasing arrow2 0.10, so this is a bit delayed on my end. What I would do here is to have a test where we have a pair `(decompressed, compressed): (Vec<u8>, Vec<u8>)` obtained from any of the packages, and test that we can roundtrip it with both feature flags.

This requires 1 test (with the pair) and a new entry in the ci / github workflows with the wasm/lz4_flex feature active, to show that the test runs on both cases. Does it make sense?

**Review by jorgecarleitao — APPROVED** [review]
Sorry, I missed the test. It looks good to me. Thanks again!

**Comment by kylebarron** [comment]
I did previously add the line in `test.yml` to run the existing tests with `lz4_flex`, so maybe that resolved your question from above.

But I'm still getting issues when trying to actually test reading a minimal parquet file. And it appears to not work either with the `lz4` feature or with the `lz4_flex` feature.

I created a simple pure-rust script here (https://github.com/kylebarron/parquet-wasm/pull/36/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fc). When I run with the `lz4` feature, I get:

```
> cargo run --no-default-features --features arrow2 --features parquet_compression_lz4
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExternalFormat("underlying IO error: LZ4 error: ERROR_frameType_unknown")', src/main.rs:22:33
```

When I run with the `lz4_flex` feature, I get:

```
> cargo run --no-default-features --features arrow2 --features parquet_compression_lz4_flex
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExternalFormat("underlying IO error: WrongMagicNumber")', src/main.rs:22:33
```

That's when reading [this Parquet file](https://github.com/kylebarron/parquet-wasm/blob/bfd6943ef693cdb673279911299612ef2a8081de/tests/data/1-partition-lz4.parquet) created by [this Python script](https://github.com/kylebarron/parquet-wasm/blob/bfd6943ef693cdb673279911299612ef2a8081de/tests/data/generate_data.py). And it's readable in Pyarrow:
```py
In [2]: import pyarrow.parquet as pq

In [3]: pq.ParquetFile('1-partition-lz4.parquet').read()
Out[3]:
pyarrow.Table
str: string
uint8: uint8
int32: int32
bool: bool
```

**Comment by jorgecarleitao** [comment]
Ok, main lz4 has been fixed and has tests for lz4 (against pyarrow). This should unblock us here :)

**Comment by jorgecarleitao** [comment]
let me know if you need any help or guidance. We may also ping the developer of lz4_flex for help here.

**Comment by kylebarron** [comment]
I haven't had time to look at this this week. That said, even if the CI were green, I'd want to test this against files created with the the original LZ4 compression (and from pyarrow), to make sure we're using the API correctly in both cases. For example, [the failing CI test](https://github.com/jorgecarleitao/parquet2/blob/59e8366ada5d383de8c68e1f12fbc285972335bf/src/compression.rs#L229-L232) looks to be a simple round trip of compression and decompression, and while the LZ4 flex docs have a [simple example](https://docs.rs/lz4_flex/latest/lz4_flex/#example-block-format-roundtrip) of block format roundtrip, using those functions might satisfy this CI test, but not the actual Parquet spec.

**Comment by jorgecarleitao** [comment]
Rebased against main and fixed the issue here #124 . Could you take a look @kylebarron and see if it addresses your concerns?

**Comment by jorgecarleitao** [comment]
Closed (done as part of #124 )

**Pull request closed without merging**
