### PR TITLE
Simplified API to write files

### PR DESCRIPTION
**Pull request by jorgecarleitao**
This simplifies the API to write a file by giving the user more control over when to emit a Row group to write.

Thanks to /u/dexterduck for the feedback on [reddit](https://www.reddit.com/r/rust/comments/s1nuqd/comment/hsaxsy3/?utm_source=share&utm_medium=web2x&context=3) that led to this PR!

### CODE REVIEW

**Review by dexterduck — APPROVED** [review]
Looks good to me!

Would be convenient to have an interface for writing Parquet files that implements `Sink` but I'd be happy to put in an issue for that since it's likely out of scope of this PR.

**Comment by jorgecarleitao** [comment]
Thanks @dexterduck ! You mean `futures::Sink`?

**Comment by dexterduck** [comment]
@jorgecarleitao yep! It's a relatively minor thing but it would be nice to have an interface that implements `futures::Sink<RowGroupIter<'_, _>>` where closing the sink writes the Parquet footer and then closes the underlying writer.
Kind of provides the best of both worlds since you can write row by row if needed, but you can also use `futures::StreamExt::forward` to fully write out a stream of row groups to a file in a single call.

**Comment by jorgecarleitao** [comment]
Thanks for your review, @dexterduck and suggestion. I agree. Would you be able to work on the `Sink`? I am not familiar with that API. It would be easier for someone that is familiar with it.

**Comment by dexterduck** [comment]
Sure, I'll give it a shot and put a PR in!

**Pull request merged**
